server:
  port: 8086
mass-hotel:
  host: 121.41.100.147
  db:
    port: 3306
    database: mass_hotel
    username: root
    password: root
  redis:
    port: 6379
    database: 0
  rabbitmq:
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    prefetch: 3
  minio:
    port: 9005
    bucket: mass-hotel
    username: minioadmin
    password: minioadmin

alipay:
  app-id: 9021000135657160    #应用Id
  seller-id: 2088721032410460  #商家Id
  gateway-url: https://openapi-sandbox.dl.alipaydev.com/gateway.do  # 支付宝网关
  # 应用私钥
  merchant-private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCh+vT33IjHASpscLvk6x32xKKi60JuBJ4AX6nbuU6c1KIPZQyGUzT1VhOjBx8XRUZAF7QLhiNiz4S41efug1AaMrRrMtXN3UnsnkqcOZeW4cM59XS3XnlBfpPZJdY2j547bjGuorr1+U6x5dF9tddjXyoWIwSknbR9TX9QM+i32CEJbQ/+vEwrVu2JLEfQmiiHm72vREJkxu1sk9jnYTidY01BEh9XQ/etNcMRdSGwe1joYdu/cpr4MdCzjbiQzAEX+mEB9Nm58VcVRGcqiILUVNZOXuOwt0Yk+N+SleS7nLvfTxS1+fOiVmacwM9+swnYweBwF9MoYPSdg6p99SkzAgMBAAECggEAOo8sstMSy8c7HBshgqARpB3woi+lQ3r92Cq9kMcMiZxBvokMnx9DvRJSZRT1A4ey3wbyu1vSPS3C0MPcZpkog2AjY8HsE9HVoOqVFKepiw2xc6mueYB5G9l0AAQyzmTbkqbC5VzFdJmd/qiUNPthk/Zak8gzLIQrNUWoKkmp75RrGBjLW+67Rg9DN8oSXWOvaysCOc/CWH6waAzPjyCpEdzH1nuL2R+nBa163bb3aA3W6wAnk4zN1O3HlDRkcjUMaji9wjRbWtQhUGFB6kLjj0jDf501J0V0TjBWtqfiYZREvnDCdE53/NcUXTL6GNxMqVXu9/2g9sbkbvJaSKFBEQKBgQDL4ipyvKtbljwvS4+Kks1IQvNH3W/2wZ4fDGxpD8lxuAHqpVzo/Om0f+WICvliTfpQUaGKKeMFpYpfgFC0jFoBL99SEIVVyetfKqgyGSv8X87FsYeMVED/YYJ2cNsgGKoHGtWbh7fn9KxQBrTqr0mD6F9KLxnXDRsToMxd2nBLSQKBgQDLYrW5e73b3GZq4WZ5t3v7Y9jcoUh6hxwL8dK1kRPvBQpSnTopq+yMT8lN3e86lPBFJCHepSXwmvmu9gSpRYHHYifqmJi9ojZO00xCQUW6ljs+UvMlDGm0QNMYkhVCMewJOLgAmPfCRwn38MKyxknhgOTY5jE41hzL4xFKbIb0mwKBgHkfVYRwXYS9jeezBgWXDOl/DLSG8vsvL1bWtJj9zfkHDexubPHlPpoC2UOm8VzbYnfQ5x0DoWE7ZSczPb7lGptV61//fJborDIPT3jjx2PZLyf3PcW6UBrnvO/MQAGjZW9vG7OYP0NH8g5gzZ4WoKACromNzdYabRmOD5s6KDgxAoGAaFg5MXMpwd2+ccE4SOP46M2eGfto6uvcWMh1OQ+4cV1doWrmxzBcSNQ6TAe7z4tQBbj243pJD7sCtF+lno55eaiDIBmv60KIqEJBkpBYTNT8igoWkoBezsqfQrDX1UE1frmptSzFl9fIZnsP+JZAmz/8qMbYo/c9iODzIwKw7lcCgYEAgbjHp/0KyttQRKGQuKYaGKB6S/ItMp1RMNxZuh9FIc7WZn+2Kzmq1necNmsrmQnSfkYnwV1ZPBP5KurZ2my6zXQMTgVkiM8/m2xo+t5KxsCfp20RqeI4oWWlhRaLQDWGbKOL7dAsOroAOmCvUHTfmV1i29nA4rCv4KGeAtF3nn0=
  # 支付宝公钥
  alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApVBLdcOYYahRbSNVqR61o9RlweQiWUV2+LDcNvLsxDr6pSwOGIO27LvYgHRf/S3oLL6liOOWZNH2fG6psltUPbmI54DhJNlKMMt/3eqKouYY5xUO4RbMcCQgdUfbmbdAKnxgs2QSvDRFTt1bS3KyMMNRjTDceX1KQJTU5zDoxcrTMl1qBRcYrWLdcn9XXBfwR8OPRDFCtI2dmworiCx052eEOgCXHA2Y9dxRRkVA6oO+Pqcyj1WQAwyu6SKzqVvjSxoK88kYx2w3u5L4RrOGWWpoRKnqYbQVuH8v4C5td9c6EjICbmsnbsiSqrIeweAaHFkzAdED+X8HrILnOpBxLwIDAQAB
  # AES对称加密
  content-key: 2llZgn/XguFOx6kBjcgSmg==
  # 支付成功 同步回调页面
  return-url: http://localhost:3000/home/userInfo
  # 异步回调接口
  notifyUrl:  http://hhlwyl.free.idcfengye.com/alipay/notify