server:
  port: 8087
mass-hotel:
  host: 121.41.100.147
  db:
    port: 3306
    database: mass_hotel
    username: root
    password: root
  redis:
    port: 6379
    database: 0
  rabbitmq:
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    prefetch: 3
  minio:
    port: 9005
    bucket: mass-hotel
    username: minioadmin
    password: minioadmin
    


spring:
  datasource:
    url: jdbc:mysql://${mass-hotel.host}:${mass-hotel.db.port}/${mass-hotel.db.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${mass-hotel.db.username}
    password: ${mass-hotel.db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${mass-hotel.host:121.41.100.147}
      port: ${mass-hotel.redis.port:6379}
      database: ${mass-hotel.redis.database:0}
      timeout: 1000
    lettuce:
      pool:
        max-active: 8  # 连接池中的最大活跃连接数
        max-idle: 8    # 连接池中的最大空闲连接数
        min-idle: 0    # 连接池中的最小空闲连接数
        max-wait: -1ms # 连接池获取连接的最大等待时间，-1表示无限等待