#单节点模式配置
singleServerConfig:
  #节点地址
  address: redis://192.168.64.100:6379
  #发布和订阅连接的最小空闲连接数
  subscriptionConnectionMinimumIdleSize: 1
  #发布和订阅连接池大小
  subscriptionConnectionPoolSize: 50
  #最小空闲连接数
  connectionMinimumIdleSize: 32
  #连接池大小
  connectionPoolSize: 64
  #数据库编号 0-15
  database: 2
  #连接空闲超时，单位：毫秒
  idleConnectionTimeout: 10000
  #连接超时，单位：毫秒
  connectTimeout: 10000
  #命令等待超时，单位：毫秒
  timeout: 3000
  #命令失败重试次数
  retryAttempts: 3
  #命令重试发送时间间隔，单位：毫秒
  retryInterval: 1500
  #单个连接最大订阅数量
  subscriptionsPerConnection: 5
  #客户端名称
  clientName: null
#线程池数量
threads: 0
#Netty线程池数量
nettyThreads: 0
#对象编码
codec: !<org.redisson.codec.JsonJacksonCodec> { }
#传输模式
transportMode: NIO

#集群配置 出节点地址外，其他同单节点配置
#clusterServersConfig:
#  nodeAddresses:
#    - "地址1"
#    - "地址2"